manipulator_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_01
    - joint_02
    - joint_03
    - joint_04
  gains:
    joint_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_04:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_gripper1
    - joint_gripper2
  gains:
    joint_gripper1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_gripper2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
manipulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_01
    - joint_02
    - joint_03
    - joint_04
  gains:
    joint_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_04:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_gripper1
    - joint_gripper2
  gains:
    joint_gripper1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_gripper2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1